<?php 
/**
  * implements hook_preprocess_views_view_field
*/
function review_list_preprocess_views_view_field(&$variables) {
  $variables['#cache']['max-age'] = 0;
  $view = $variables['view'];
  $field = $variables['field'];
  if ($view->storage->id() == 'reviews_list' && $view->current_display == 'page_1' && $field->field == 'field_article') {
    $review_api_connector_service = \Drupal::service('review_list.api_connector');
    if (!empty($variables['row']->_entity->field_article->getValue())) {
      $RefNid = $variables['row']->_entity->field_article->getValue()[0]['target_id'];
      $review = $review_api_connector_service->discoverArticles($RefNid);
      $variables['output'] = !empty($review->title) ? $review->title : 'No Article attached to this Review!';
    }
  }
}
